### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xzx17612724237** [zyronon/douyin#42]
我拉取到代码并解压后安照您的方法运行项目报错了！
我的node 版本是  v14.21.3
报错内容为： 
failed to load config from C:\Users\Administrator\Desktop\新建文件夹\douyin-master\vite.config.js
error when starting dev server:
C:\Users\Administrator\Desktop\新建文件夹\douyin-master\node_modules\@vue-macros\api\dist\index.js:392
        optional ||= property.optional;
                 ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/Administrator/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9/douyin-master/node_modules/vite/dist/node/chunks/dep
-52909643.js:66353:17)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\新建文件夹\douyin-master\node_modules\@vue-macros\better-define\dist\chunk-QOUBAYKX.js:13:12)

好像是提示的路径里面有语法不能识别，我尝试着删除 node_modules包 和package-lock.json  重新下载还是一样的报错
![Snipaste_2024-03-25_16-43-26](https://github.com/zyronon/douyin/assets/105836230/24a7af3e-6e42-41bb-acca-f1bd837c0c87)
![Snipaste_2024-03-25_16-43-26](https://github.com/zyronon/douyin/assets/105836230/9671905a-5657-41ad-9a27-038a59c838d3)

希望您有时间看到的话回复一下这个问题，辛苦了

**Comment by zyronon** [comment]
1、不要用中文路径名

2、node升到16.14以上。node多个版本管理可以用nvm这个工具
